### ISSUE TITLE
gh-pages branch is not pushed to VSTS

### ISSUE THREAD

**Issue by peterennisrda** [kinsidar/DFAQ#1]
Q: Why is gh-pages not pushed to VSTS?

Add the Q&A to your DFAQ

![capture1182](https://user-images.githubusercontent.com/1280523/32083068-d4d6e6f0-ba74-11e7-9089-bcafdb029de4.PNG)

**Comment by kinsidar** [comment]
Added the Q&A here:

https://kinsidar.github.io/DFAQ/docs/Q&A.html

Thanks!
