### ISSUE TITLE
Setup documentation not provided

### ISSUE THREAD

**Issue by peterennisrda** [kinsidar/DFAQ#2]
You seem to have solved the following question:
Q: How do I fork from VSTS to GitHub?

The evidence is in the existence of the repo.

Add the Q&A to the DFAQ describing the process.
Link to other setup examples you have made where relevant.

**Comment by kinsidar** [comment]
Here's the documentation:

https://kinsidar.github.io/DFAQ/docs/documentation/versionControl/VSTStoGithub.html

Thanks!
