### ISSUE TITLE
How do I push all branches from GitHub to VSTS?

### ISSUE THREAD

**Issue by peterennisrda** [kinsidar/DFAQ#3]
Ref: #1 
git allows pushing branches.
gh-pages may not be used by VSTS but it is still a valid
branch that can be also kept in the VSTS repo.

Find the command. Push the branch. Show the result. Update the FAQ.

**Comment by kinsidar** [comment]
Updated FAQ!

https://kinsidar.github.io/DFAQ/Q&A.html
